language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DJANGO=2.2 DB=postgres
# command to install dependencies
install:
  - pipenv install
# setup database configuration
before_script:
  - wget "https://github.com/mozilla/geckodriver/releases/download/v0.28.0/geckodriver-v0.28.0-linux64.tar.gz"
  - tar xfz geckodriver-v0.28.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - psql -c "CREATE DATABASE offproducts;" -U postgres
  - psql -c "CREATE USER cibuild PASSWORD 'cibuild';" -U postgres
  - psql -c "ALTER USER cibuild CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE offproducts to cibuild;" -U postgres
  # command to run tests
script:
  - python manage.py test
