language: python
python:
- '3.7'
services:
- postgresql
env:
- DJANGO=2.2 DB=postgres
addons:
  ssh_known_hosts: 51.159.66.3
install:
- pipenv install
before_script:
- psql -c "CREATE DATABASE offproducts;" -U postgres
- psql -c "CREATE USER cibuild PASSWORD 'cibuild';" -U postgres
- psql -c "ALTER USER cibuild CREATEDB;" -U postgres
- psql -c "GRANT ALL PRIVILEGES on DATABASE offproducts to cibuild;" -U postgres
script:
- python manage.py test
before_deploy:
- eval "$(ssh-agent -s)"
deploy:
  provider: script
  skip_cleanup: true
  script:
    openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
      -in deploy_rsa.enc -out /tmp/deploy_rsa -d
    && chmod 600 /tmp/deploy_rsa
    && ssh-add /tmp/deploy_rsa
    && git remote add deploy slesouef@51.159.66.3:~/django-web/
    && git push deploy HEAD:release/production
  on:
    branch: release/production