language: python
python:
  - "3.7"
services:
  - postgresql
env:
  - DJANGO=2.2 DB=postgres
# command to install dependencies
install:
  - pipenv install
# setup database configuration
before_script:
  - psql -c "CREATE DATABASE offproducts;" -U postgres
  - psql -c "CREATE USER travis PASSWORD 'travis';" -U postgres
  - psql -c "ALTER USER travis CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES on DATABASE offproducts to travis;" -U postgres
  # command to run tests
script:
  - python manage.py test
