# Generated by Django 2.2.3 on 2019-07-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_products_favorites'),
        ('accounts', '0004_auto_20190519_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites', to='search.Products'),
        ),
    ]
