# Generated by Django 2.2 on 2019-04-19 08:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('brand', models.CharField(max_length=254)),
                ('quantity', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('rating', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('image', models.URLField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Categories')),
                ('favorites', models.ManyToManyField(related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(blank=True, max_length=254)),
                ('energy', models.CharField(blank=True, max_length=254)),
                ('energy_per100', models.CharField(blank=True, max_length=254)),
                ('energy_unit', models.CharField(blank=True, max_length=254)),
                ('fat', models.CharField(blank=True, max_length=254)),
                ('fat_per100', models.CharField(blank=True, max_length=254)),
                ('fat_unit', models.CharField(blank=True, max_length=254)),
                ('saturatedFat', models.CharField(blank=True, max_length=254)),
                ('saturatedFat_per100', models.CharField(blank=True, max_length=254)),
                ('saturatedFat_unit', models.CharField(blank=True, max_length=254)),
                ('carbohydrates', models.CharField(blank=True, max_length=254)),
                ('carbohydrates_per100', models.CharField(blank=True, max_length=254)),
                ('carbohydrates_unit', models.CharField(blank=True, max_length=254)),
                ('sugar', models.CharField(blank=True, max_length=254)),
                ('sugar_per100', models.CharField(blank=True, max_length=254)),
                ('sugar_unit', models.CharField(blank=True, max_length=254)),
                ('fiber', models.CharField(blank=True, max_length=254)),
                ('fiber_per100', models.CharField(blank=True, max_length=254)),
                ('fiber_unit', models.CharField(blank=True, max_length=254)),
                ('proteins', models.CharField(blank=True, max_length=254)),
                ('proteins_per100', models.CharField(blank=True, max_length=254)),
                ('proteins_unit', models.CharField(blank=True, max_length=254)),
                ('salt', models.CharField(blank=True, max_length=254)),
                ('salt_per100', models.CharField(blank=True, max_length=254)),
                ('salt_unit', models.CharField(blank=True, max_length=254)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.Products')),
            ],
        ),
    ]
