# Generated by Django 2.2.3 on 2019-08-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('brand', models.CharField(max_length=254)),
                ('quantity', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True)),
                ('rating', models.CharField(max_length=1)),
                ('url', models.URLField()),
                ('image', models.URLField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionalValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving_size', models.CharField(blank=True, max_length=254)),
                ('energy', models.CharField(blank=True, max_length=254)),
                ('energy_per100', models.CharField(blank=True, max_length=254)),
                ('energy_unit', models.CharField(blank=True, max_length=254)),
                ('fat', models.CharField(blank=True, max_length=254)),
                ('fat_per100', models.CharField(blank=True, max_length=254)),
                ('fat_unit', models.CharField(blank=True, max_length=254)),
                ('saturatedFat', models.CharField(blank=True, max_length=254)),
                ('saturatedFat_per100', models.CharField(blank=True, max_length=254)),
                ('saturatedFat_unit', models.CharField(blank=True, max_length=254)),
                ('carbohydrates', models.CharField(blank=True, max_length=254)),
                ('carbohydrates_per100', models.CharField(blank=True, max_length=254)),
                ('carbohydrates_unit', models.CharField(blank=True, max_length=254)),
                ('sugar', models.CharField(blank=True, max_length=254)),
                ('sugar_per100', models.CharField(blank=True, max_length=254)),
                ('sugar_unit', models.CharField(blank=True, max_length=254)),
                ('fiber', models.CharField(blank=True, max_length=254)),
                ('fiber_per100', models.CharField(blank=True, max_length=254)),
                ('fiber_unit', models.CharField(blank=True, max_length=254)),
                ('proteins', models.CharField(blank=True, max_length=254)),
                ('proteins_per100', models.CharField(blank=True, max_length=254)),
                ('proteins_unit', models.CharField(blank=True, max_length=254)),
                ('salt', models.CharField(blank=True, max_length=254)),
                ('salt_per100', models.CharField(blank=True, max_length=254)),
                ('salt_unit', models.CharField(blank=True, max_length=254)),
                ('pid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='search.Products')),
            ],
        ),
    ]
