# Generated by Django 2.2.3 on 2019-07-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190511_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='favorites',
        ),
    ]
